# Generated by Django 5.0.7 on 2024-07-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                blank=True, default="media/default.jpg", null=True, upload_to="media"
            ),
        ),
    ]
