# Generated by Django 5.0.7 on 2024-07-31 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_by', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('unit_name', models.CharField(max_length=255)),
                ('approved_by', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('recruitment_type', models.CharField(max_length=50)),
                ('vacant_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VacancyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('resigned_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('recruitment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='profileapp.recruitmentform')),
            ],
        ),
    ]
