# Generated by Django 5.0.7 on 2024-08-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentform',
            name='job_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentform',
            name='vacant_position',
            field=models.PositiveIntegerField(),
        ),
    ]
