# Generated by Django 5.0.7 on 2024-08-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_recruitmentform_job_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancydetail',
            name='location',
        ),
        migrations.AddField(
            model_name='recruitmentform',
            name='location',
            field=models.CharField(default='OHQ', max_length=50),
            preserve_default=False,
        ),
    ]
