# Generated by Django 5.0.7 on 2024-08-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_remove_vacancydetail_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('utility', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utility_remarks', models.CharField(blank=True, max_length=255)),
                ('driver_wages', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_wages_remarks', models.CharField(blank=True, max_length=255)),
                ('service_staff_wages', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_staff_wages_remarks', models.CharField(blank=True, max_length=255)),
                ('security_staff_wages', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_staff_wages_remarks', models.CharField(blank=True, max_length=255)),
                ('leave_fare_assistance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leave_fare_assistance_remarks', models.CharField(blank=True, max_length=255)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_cost_remarks', models.CharField(blank=True, max_length=255)),
                ('gas_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas_cost_remarks', models.CharField(blank=True, max_length=255)),
                ('repair_maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('repair_maintenance_remarks', models.CharField(blank=True, max_length=255)),
                ('tyres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tyres_remarks', models.CharField(blank=True, max_length=255)),
                ('battery', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('battery_remarks', models.CharField(blank=True, max_length=255)),
                ('car_denting_painting', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car_denting_painting_remarks', models.CharField(blank=True, max_length=255)),
                ('car_decorations', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car_decorations_remarks', models.CharField(blank=True, max_length=255)),
                ('toll', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('toll_remarks', models.CharField(blank=True, max_length=255)),
                ('others', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('others_remarks', models.CharField(blank=True, max_length=255)),
                ('telephone', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('telephone_remarks', models.CharField(blank=True, max_length=255)),
                ('mobile_set', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mobile_set_remarks', models.CharField(blank=True, max_length=255)),
                ('medical_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medical_expense_remarks', models.CharField(blank=True, max_length=255)),
                ('medical_expense_surgery', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medical_expense_surgery_remarks', models.CharField(blank=True, max_length=255)),
                ('total_taka', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('advance_drawn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expenses_as_above', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
