# Generated by Django 5.0.7 on 2024-08-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0011_alter_expensereport_advance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseReport',
        ),
    ]
