# Generated by Django 5.0.7 on 2024-08-13 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0012_delete_expensereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('utility', models.CharField(max_length=255)),
                ('utility_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_wages', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_wages_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('service_staff_wages', models.CharField(blank=True, max_length=255, null=True)),
                ('service_staff_wages_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('security_staff_wages', models.CharField(blank=True, max_length=255, null=True)),
                ('security_staff_wages_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('leave_fare_assistance', models.CharField(blank=True, max_length=255, null=True)),
                ('leave_fare_assistance_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_cost_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('gas_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('gas_cost_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('repair_maintenance', models.CharField(blank=True, max_length=255, null=True)),
                ('repair_maintenance_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('tyres', models.CharField(blank=True, max_length=255, null=True)),
                ('tyres_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('battery', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('car_denting_painting', models.CharField(blank=True, max_length=255, null=True)),
                ('car_denting_painting_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('car_decorations', models.CharField(blank=True, max_length=255, null=True)),
                ('car_decorations_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('toll', models.CharField(blank=True, max_length=255, null=True)),
                ('toll_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('others', models.CharField(blank=True, max_length=255, null=True)),
                ('others_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_set', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_set_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_expense', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_expense_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_expense_surgery', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_expense_surgery_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('total_taka', models.CharField(max_length=255)),
                ('advance', models.CharField(max_length=255)),
                ('expenses_as_above', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_due', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
