# Generated by Django 5.0.7 on 2024-08-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0015_remove_profile_desc_remove_profile_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='purpose',
        ),
    ]
