# Generated by Django 5.0.7 on 2024-08-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0017_remove_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='advance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
