# Generated by Django 5.0.7 on 2024-08-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0018_alter_expense_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='utility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
